#!/bin/bash

service='avahi-daemon.service'

while true ; do
    if systemctl is-active "$service" > /dev/null 2>&1 ; then
        ping -c 1 "$(hostname).local" > /dev/null 2>&1 || {
            dotpi echo_info "$(hostname): restart avahi-daemon"
            sudo systemctl restart "$service"
        }
    fi
    sleep 60
done

