#!/bin/bash

local_file="$(dotpi readlink_follow "$0")"
local_path="$(dirname -- "$local_file")"

source "${local_path}/dotpi_jackd.bash"

echo "dotpi_jackd_command"

echo "ENV: ${DOTPI_JACKD_ENVIRONMENT[@]}"
echo "ARGS: ${DOTPI_JACKD_ARGUMENTS[@]}"

for e in "${DOTPI_JACKD_ENVIRONMENT[@]}" ; do
    export "$e"
done

while IFS= read -r output ; do
    jackd_pid="$!"
    # forward output
    echo "$output"
    if [[ "$output" =~ JackAudioDriver.*stopping ]] ; then
        dotpi echo_error "jackd stopped, it will be killed."
        kill "$jackd_pid"
    fi

    if [[ "$output" =~ JackAudioDriver.*Process.*error ]] ; then
        dotpi echo_error "jackd process error, it will be killed."
        kill "$jackd_pid"
    fi

done < <( jackd "${DOTPI_JACKD_ARGUMENTS[@]}" 2>&1)

